name: PDF → PDF 1.4 (multi-engine, logs, autocommit)

concurrency:
  group: pdf-downgrade-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Opcjonalna ścieżka do jednego PDF-a (np. input/plik.pdf). Pusta = skanuj input/, potem całe repo.'
        required: false
        default: ''
      pdfsettings:
        description: 'Profil Ghostscript: /prepress, /printer, /ebook, /screen'
        required: false
        default: '/prepress'
      allow_raster_fallback:
        description: 'Zezwól na fallback rastrowy (true/false)'
        required: false
        default: 'true'
  push:
    paths:
      - "input/**.pdf"
      - "input/**.PDF"

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Show repo tree & find PDFs (debug)
        run: |
          echo "== CWD =="; pwd
          echo "== Repo tree =="; ls -lahR || true
          echo "== PDFs in input/ (any case) =="
          find input -type f \( -iname "*.pdf" -o -iname "*.PDF" \) -print || true

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript qpdf mupdf-tools poppler-utils
          gs -v || true
          qpdf --version || true
          mutool -v || true
          pdftocairo -v || true

      - name: Convert PDFs (GS → QPDF+GS → MuPDF+GS → Raster)
        shell: bash
        env:
          PDFSETTINGS: ${{ github.event.inputs.pdfsettings && github.event.inputs.pdfsettings || '/prepress' }}
          ALLOW_RASTER: ${{ github.event.inputs.allow_raster_fallback && github.event.inputs.allow_raster_fallback || 'true' }}
          INPUT_PATH: ${{ github.event.inputs.path && github.event.inputs.path || '' }}
        run: |
          set -euo pipefail
          mkdir -p output logs

          # Zbierz pliki wejściowe
          declare -a files=()
          if [[ -n "$INPUT_PATH" ]]; then
            files=( "$INPUT_PATH" )
          else
            mapfile -t files < <(find input -type f \( -iname "*.pdf" -o -iname "*.PDF" \) -print 2>/dev/null || true)
            if (( ${#files[@]} == 0 )); then
              echo "Brak w input/. Skanuję całe repo (bez .git oraz output/)..."
              mapfile -t files < <(find . -type f \( -iname "*.pdf" -o -iname "*.PDF" \) ! -path "./.git/*" ! -path "./output/*" -print)
            fi
          fi

          if (( ${#files[@]} == 0 )); then
            echo "ERROR: Nie znaleziono żadnych PDF-ów." ; exit 66
          fi

          success_count=0
          fail_count=0

          for f in "${files[@]}"; do
            base="$(basename "$f")"; stem="${base%.*}"
            out="output/${stem}_PDF14.pdf"
            log="logs/${stem}.log"
            echo "=== Przetwarzam: $f ===" | tee "$log"

            # 1) Ghostscript
            if gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dBATCH \
                  -dPDFSETTINGS="${PDFSETTINGS}" \
                  -sOutputFile="$out" "$f" >>"$log" 2>&1; then
              echo "OK: Ghostscript (minimalny)" | tee -a "$log"
              ((success_count++))
              continue
            fi

            # 2) qpdf → Ghostscript
            tmp1="$(mktemp --suffix=.pdf)"
            if qpdf --linearize "$f" "$tmp1" >>"$log" 2>&1 && \
               gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dBATCH \
                  -dPDFSETTINGS="${PDFSETTINGS}" \
                  -sOutputFile="$out" "$tmp1" >>"$log" 2>&1; then
              echo "OK: qpdf + Ghostscript" | tee -a "$log"
              rm -f "$tmp1"
              ((success_count++))
              continue
            fi
            rm -f "$tmp1" || true

            # 3) MuPDF (mutool clean) → Ghostscript
            tmp2="$(mktemp --suffix=.pdf)"
            if mutool clean -gg -d "$f" "$tmp2" >>"$log" 2>&1 && \
               gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dBATCH \
                  -dPDFSETTINGS="${PDFSETTINGS}" \
                  -sOutputFile="$out" "$tmp2" >>"$log" 2>&1; then
              echo "OK: MuPDF + Ghostscript" | tee -a "$log"
              rm -f "$tmp2"
              ((success_count++))
              continue
            fi
            rm -f "$tmp2" || true

            # 4) Raster fallback (opcjonalny)
            if [[ "${ALLOW_RASTER}" == "true" ]]; then
              out_raster="output/${stem}_RASTER_PDF14.pdf"
              if pdftocairo -pdf -r 300 "$f" "output/${stem}_RASTER" >>"$log" 2>&1; then
                mv "output/${stem}_RASTER.pdf" "$out_raster"
                echo "OK: Raster fallback (pdftocairo 300 DPI)" | tee -a "$log"
                ((success_count++))
                continue
              fi
            else
              echo "Raster fallback wyłączony." | tee -a "$log"
            fi

            echo "FAIL: wszystkie metody zawiodły dla $f (patrz $log)" | tee -a "$log"
            ((fail_count++)) || true
          done

          echo "== Podsumowanie =="
          echo "Sukcesy: $success_count"
          echo "Niepowodzenia: $fail_count"
          if (( success_count == 0 )); then
            exit 255
          fi

      - name: List outputs
        run: |
          echo "== output =="; ls -lah output || true
          echo "== logs =="; ls -lah logs || true

      - name: Upload artifacts (PDFs + logs)
        uses: actions/upload-artifact@v4
        with:
          name: converted-pdfs-and-logs
          path: |
            output
            logs
          if-no-files-found: warn
          retention-days: 14

      - name: Determine target branch
        id: branch
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}" >> "$GITHUB_OUTPUT"
          echo "Using branch: ${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"

      - name: Commit & push outputs back to repo (robust)
        if: success()
        continue-on-error: true
        env:
          BRANCH: ${{ steps.branch.outputs.branch }}
        run: |
          if [ -z "$(ls -A output 2>/dev/null)" ]; then
            echo "No files in output/, nothing to commit."
            exit 0
          fi

          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin "$BRANCH" || true
          git checkout -B "$BRANCH" "origin/$BRANCH" 2>/dev/null || git checkout -B "$BRANCH"

          git add output || true
          git commit -m "Add converted PDFs ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)" || echo "No changes to commit."

          git pull --ff-only origin "$BRANCH" || echo "::warning ::Pull failed (ff-only). Continuing."
          git push origin "HEAD:$BRANCH" || echo "::warning ::Push failed (protected branch or permissions)."
