name: PDF → PDF 1.4 (multi-engine, logs, autocommit, diagnostics)

concurrency:
  group: pdf-downgrade-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Opcjonalna ścieżka do jednego PDF-a (np. input/plik.pdf). Pusta = skanuj input/, potem całe repo.'
        required: false
        default: ''
      pdfsettings:
        description: 'Profil Ghostscript: /prepress, /printer, /ebook, /screen'
        required: false
        default: '/prepress'
      allow_raster_fallback:
        description: 'Zezwól na fallback rastrowy (true/false)'
        required: false
        default: 'true'
      raster_dpi:
        description: 'DPI dla fallbacku rastrowego (np. 300)'
        required: false
        default: '300'
  push:
    paths:
      - "input/**.pdf"
      - "input/**.PDF"

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Show repo tree &
